export const ACTION_TYPE = {
    SELECTED_CONVERSATION_CHANGED: "SELECTED_CONVERSATION_CHANGED",
    CONVERSATIONS_REQUESTED: "CONVERSATIONS_REQUESTED",
    DELETE_CONVERSATION: "DELETE_CONVERSATION",
    CREATE_MESSAGE: "CREATE_MESSAGE",
    CREATED_MESSAGE: "CREATED_MESSAGE"
};