export enum ENUM_PAGINATION_ORDER_DIRECTION_TYPE {
    ASC = 'ASC',
    DESC = 'DESC',
}

export enum ENUM_PAGINATION_FILTER_CASE_OPTIONS {
    UPPERCASE = 'UPPERCASE',
    LOWERCASE = 'LOWERCASE',
}

export enum ENUM_PAGINATION_FILTER_DATE_TIME_OPTIONS {
    START_OF_DAY = 'START_OF_DAY',
    END_OF_DAY = 'END_OF_DAY',
}
